### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cyouh95** [tommygebru/review-dasmotos#5]
(Exceeds Expectations)

Nice job with this project! It looks like you have a solid understanding of how HTML and CSS work together for display of content. And keep up the good work on proper indenting and formatting of your code - makes things easy to read and follow!

As a further challenge, try expanding this page and play around with adding some of your own elements to it. As you do, look out for ways to simplify your code and reduce the amount of repetition or unneeded code (#3).

**Comment by tommygebru** [comment]
HP reference?

Thanks for the taking the time to review my project, look forward to hearing from you again @cyouh95
